cursor #e4e2e3
cursor_text_color #c7c6c7

foreground            #e4e2e3
background            #131314
selection_foreground  #2b3137
selection_background  #c1c7ce
url_color             #bcc8d3

# black
color8   #919091
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0
# green
color2   #8aac8b
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #bcc8d3
color12 #a39ec4

# magenta
color5   #b7c9d9
color13  #d3e5f5
# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
